version: "3"
services:
  f1-live:
    container_name: "f1-live"
    network_mode: "bridge"
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "127.0.0.1:5100:3000"
      - "127.0.0.1:5101:3001"
    environment:
      - NEXT_PUBLIC_WS_URL=https://live.tracinginsights.com
    restart: unless-stopped
